version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: docker/dev/Dockerfile
    ports:
      - "8000:8000"
      - "8080:8080"
    volumes:
      - ../app:/app/app
      - ../cpp:/app/cpp
    environment:
      - PYTHONPATH=/app:/app/cpp/build
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
