version: '3.8'

services:
  frontend:
    build:
      context: ..
      dockerfile: docker/dev/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - FRONTEND_HOST=0.0.0.0
      - FRONTEND_PORT=8000
      - BACKEND_HOST=backend
      - BACKEND_PORT=8001
      - SECURITY_LEVEL=high
      - PYTHONUNBUFFERED=1
    volumes:
      - ../app:/app/app
      - ./docker-compose.yml:/app/docker-compose.yml
    depends_on:
      - backend
      - redis
    command: uvicorn app.frontend.main:app --host 0.0.0.0 --port 8000 --reload

  backend:
    build:
      context: ..
      dockerfile: docker/dev/Dockerfile
    environment:
      - BACKEND_HOST=0.0.0.0
      - BACKEND_PORT=8001
      - MODEL_NAME=distilbert-base-uncased
      - TOXIC_THRESHOLD=0.7
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PYTHONUNBUFFERED=1
    volumes:
      - ../app:/app/app
      - ../cpp:/app/cpp
      - ./docker-compose.yml:/app/docker-compose.yml
    depends_on:
      - redis
    command: uvicorn app.backend.main:app --host 0.0.0.0 --port 8001 --reload

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  # Uncomment to enable monitoring with Prometheus and Grafana
  # prometheus:
  #   image: prom/prometheus:latest
  #   ports:
  #     - "9090:9090"
  #   volumes:
  #     - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
  #   command:
  #     - '--config.file=/etc/prometheus/prometheus.yml'
  #   depends_on:
  #     - frontend
  #     - backend

  # grafana:
  #   image: grafana/grafana:latest
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - grafana_data:/var/lib/grafana
  #   environment:
  #     - GF_SECURITY_ADMIN_PASSWORD=admin
  #   depends_on:
  #     - prometheus

volumes:
  redis_data:
  # grafana_data:
