name: Build & Run

on:
  push:
    branches: [ '*' ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Compose
        uses: docker/setup-buildx-action@v3

      - name: Build and start stack
        run: |
          docker compose -f docker/dev/docker-compose.yml up -d --build

      - name: Wait for frontend to be ready
        run: |
          timeout=60
          until curl -s http://localhost:8000/status | grep '"status"' || [ $timeout -eq 0 ]; do
            echo "Waiting for frontend..."; sleep 2; timeout=$((timeout-2));
          done
          if [ $timeout -eq 0 ]; then
            echo "Frontend did not become ready"; exit 1;
          fi

      - name: Show running containers
        run: docker ps -a

      - name: Shutdown stack
        if: always()
        run: docker compose -f docker/dev/docker-compose.yml down
