name: Build and Push Docker image

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: Render

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/production/Dockerfile.frontend
          push: ${{ github.event_name == 'push' }}
          load: ${{ github.event_name == 'pull_request' }}
          tags: ghcr.io/zivtalyas/safe-input-proxy-frontend:latest

      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/production/Dockerfile.backend
          push: ${{ github.event_name == 'push' }}
          load: ${{ github.event_name == 'pull_request' }}
          tags: ghcr.io/zivtalyas/safe-input-proxy-backend:latest

      - name: Trigger Render deploy (frontend)
        if: github.event_name == 'push'
        run: |
          curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK_URL_FORNT }}"

      - name: Trigger Render deploy (backend)
        if: github.event_name == 'push'
        run: |
          curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK_URL_BACKEND }}"