name: Build and Push Docker image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: Render

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/production/Dockerfile.frontend
          push: true
          tags: ghcr.io/zivtalyas/safe-input-proxy-frontend:latest

      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/production/Dockerfile.backend
          push: true
          tags: ghcr.io/zivtalyas/safe-input-proxy-backend:latest

      - name: Trigger Render deploy (frontend)
        run: |
          curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK_URL_FORNT }}"

      - name: Trigger Render deploy (backend)
        run: |
          curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK_URL_BACKEND }}"

      # Optional: Notify Render to deploy the new image
      # - name: Trigger Render deploy
      #   run: |
      #     curl -X POST "https://api.render.com/deploy/srv-xxxxxx?key=YOUR_RENDER_DEPLOY_HOOK"