name: Test Cloud Deployment

on:
  pull_request:
  workflow_dispatch:

jobs:
  test-cloud:
    runs-on: ubuntu-latest
    environment: Render
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Wait for deployment to complete (main only)
        if: github.event_name == 'push'
        run: |
          echo "Waiting for Render deployment to complete..."
          sleep 60
          echo "Checking service health..."
          timeout=600
          frontend_url="${{ secrets.RENDER_FRONTEND_URL }}"
          backend_url="${{ secrets.RENDER_BACKEND_URL }}"
          if [[ ! "$frontend_url" =~ ^https?:// ]]; then
            echo "❌ Invalid frontend URL: $frontend_url"; exit 1; fi
          if [[ ! "$backend_url" =~ ^https?:// ]]; then
            echo "❌ Invalid backend URL: $backend_url"; exit 1; fi
          until [ $timeout -eq 0 ]; do
            frontend_ok=false
            backend_ok=false
            if curl -s "$frontend_url/status" | grep -q '"status"'; then frontend_ok=true; fi
            if curl -s "$backend_url/health" | grep -q '"status"'; then backend_ok=true; fi
            if [ "$frontend_ok" = true ] && [ "$backend_ok" = true ]; then break; fi
            sleep 20; timeout=$((timeout-20));
          done
          if [ $timeout -eq 0 ]; then
            echo "❌ Services did not become ready in Render within timeout"; exit 1; fi

      - name: Run test suite
        run: |
          python -m unittest tests/test_api.py -v
        env:
          PROXY_BASE_URL: ${{ secrets.RENDER_FRONTEND_URL }} 