name: API Tests

on:
  push:
    branches: [ '*' ]
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      PROXY_BASE_URL: http://localhost:8000
    steps:
      - uses: actions/checkout@v4

      - name: Build and start stack
        run: |
          docker compose -f docker/dev/docker-compose.yml up -d --build

      - name: Wait for frontend to be ready
        run: |
          timeout=60
          until curl -s $PROXY_BASE_URL/status | grep '"status"' || [ $timeout -eq 0 ]; do
            echo "Waiting for frontend..."; sleep 2; timeout=$((timeout-2));
          done
          if [ $timeout -eq 0 ]; then
            echo "Frontend did not become ready"; docker logs $(docker ps -q); exit 1;
          fi

      - name: Run test suite with allowed failures
        run: |
          set +e
          output=$(python -m unittest tests/test_api.py -v 2>&1)
          status=$?
          echo "$output"
          if [ $status -ne 0 ]; then
            # extract failing test method names
            fails=$(echo "$output" | grep -oP '^FAIL: \w+' | awk '{print $2}')
            allowed="test_harmful_keyword test_validate_unsafe_text test_validate_file_upload_pdf test_validate_file_upload_txt"
            for f in $fails; do
              if [[ ! " $allowed " =~ " $f " ]]; then
                echo "❌ Non-allowed test failed: $f"; exit 1
              else
                echo "⚠️ Allowed failure: $f (ignored)"
              fi
            done
          fi
          echo "✅ Test phase completed (allowed failures ignored)"

      - name: Shutdown stack
        if: always()
        run: docker compose -f docker/dev/docker-compose.yml down
