name: Test Local Containers

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Keeping manual trigger for debugging

jobs:
  test-local:
    runs-on: ubuntu-latest
    env:
      PROXY_BASE_URL: http://localhost:8000
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and start stack
        run: |
          docker compose -f docker/dev/docker-compose.yml up -d --build

      - name: Wait for frontend to be ready
        run: |
          timeout=60
          until curl -s $PROXY_BASE_URL/status | grep '"status"' || [ $timeout -eq 0 ]; do
            echo "Waiting for frontend..."; sleep 2; timeout=$((timeout-2));
          done
          if [ $timeout -eq 0 ]; then
            echo "Frontend did not become ready"; docker logs $(docker ps -q); exit 1;
          fi

      - name: Run test suite
        run: |
          python -m unittest tests/test_api.py -v

      - name: Shutdown stack
        if: always()
        run: |
          docker compose -f docker/dev/docker-compose.yml down 